[server]
Host = "0.0.0.0"
Port = "8080"

[logger]
level = "info"

[database]
Prefix = "postgresql"
DatabaseName = "postgres"
#Host = "balance_postgresdb"
#Port = ""
Host = "localhost"
Port = "5432"
UserName = "postgres"
Password = "1234512345"